hash-format = "sha256"

[[files]]
file = "config/paxi/datapack_load_order.json"
hash = "d0aaf3172f34275479f0669aa5b0a94b85788ae638f3062b948ec49d31c38293"

[[files]]
file = "config/paxi/datapacks/drowning-in-sky-datapack/data/drowning-in-sky/physics_block_properties/crimson_door.json"
hash = "c7c7f33e81d31a3ed470246be9f00166583151740df6026005a13606c17a70ac"

[[files]]
file = "config/paxi/datapacks/drowning-in-sky-datapack/data/drowning-in-sky/physics_block_properties/crimson_stems.json"
hash = "19fca55922471deedb65536279c897b2bc36acc1355c1aef7b284c875c4de448"

[[files]]
file = "config/paxi/datapacks/drowning-in-sky-datapack/data/drowning-in-sky/physics_block_properties/crimson_trapdoor.json"
hash = "e0c6f2fa73c866c1a459482ab298e0a4d3451e5239bc312077eaf9911c0bb581"

[[files]]
file = "config/paxi/datapacks/drowning-in-sky-datapack/data/drowning-in-sky/physics_block_properties/featherlight.json"
hash = "61d7f98917691cea863cee13e6db0763a584608ea0147d3c75d7a823b8b4cd09"

[[files]]
file = "config/paxi/datapacks/drowning-in-sky-datapack/data/drowning-in-sky/physics_block_properties/mace_core.json"
hash = "71f07c4bff8f1b64c3377d9059c48404a89bf64447c842540c2b5369cc16445a"

[[files]]
file = "config/paxi/datapacks/drowning-in-sky-datapack/data/drowning-in-sky/physics_block_properties/super_duper_heavy.json"
hash = "ac5ff44f4d65a3847637c1f7e25465357dd947ce62d0f73f90da8d725ee0788f"

[[files]]
file = "config/paxi/datapacks/drowning-in-sky-datapack/data/drowning-in-sky/physics_block_properties/warped_door.json"
hash = "7bdc23ec82f1da9b433f3eb0d9d3dce7932b833d5fce8be5150b0aa612c9ea8c"

[[files]]
file = "config/paxi/datapacks/drowning-in-sky-datapack/data/drowning-in-sky/physics_block_properties/warped_stems.json"
hash = "2988455e5b16d309a23c6870109cd2fd3487c1656c081d6966961cb01f3a5b49"

[[files]]
file = "config/paxi/datapacks/drowning-in-sky-datapack/data/drowning-in-sky/physics_block_properties/warped_trapdoor.json"
hash = "32411acc37250a71bc29795791eaa8178c0bec9f1cd4879049438a0df25c81b9"

[[files]]
file = "config/paxi/datapacks/drowning-in-sky-datapack/data/drowning-in-sky/tags/block/featherlight.json"
hash = "85d8a5c3146fbfc38211ef9016fe78071626fc87421f3ec5d6ed896f4b14bfdc"

[[files]]
file = "config/paxi/datapacks/drowning-in-sky-datapack/data/drowning-in-sky/tags/block/super_duper_heavy.json"
hash = "a7e31c10cc8e937bff600b3481b5302b76006488fe85d9198c6a8eb7261f6166"

[[files]]
file = "config/paxi/datapacks/drowning-in-sky-datapack/data/minecraft/dimension_type/overworld.json"
hash = "a1d7452c4b29459a11093954c11ef7c6dab90eda3368fc7f3624e18fad0b957a"

[[files]]
file = "config/paxi/datapacks/drowning-in-sky-datapack/data/minecraft/worldgen/noise_settings/overworld.json"
hash = "1487fca45fb2c6fdbf4ea3e73f23da1a7a4ae107169f1c1342fe69a109b96371"

[[files]]
file = "config/paxi/datapacks/drowning-in-sky-datapack/data/sable/tags/block/light.json"
hash = "c134f807c7fe507834a436ce06c4adde9575c2843d98331e52fda21470811ef9"

[[files]]
file = "config/paxi/datapacks/drowning-in-sky-datapack/data/sable/tags/block/super_light.json"
hash = "bc63e3c72eb7d410bf538b040a02d8ddc1f4a368765f617075ade591719c78e6"

[[files]]
file = "config/paxi/datapacks/drowning-in-sky-datapack/pack.mcmeta"
hash = "180f8d33b55ae5420b4b9d2e7714a2861fb1d421305d4052218774a6b51bb2dc"

[[files]]
file = "config/paxi/resourcepack_load_order.json"
hash = "d0aaf3172f34275479f0669aa5b0a94b85788ae638f3062b948ec49d31c38293"

[[files]]
file = "config/paxi/resourcepacks/drowning-in-sky-resourcepack/assets/drowning-in-sky/pinwheel/post/cloud_sea.json"
hash = "179fe7eeeb9f50d3d21673385ff9bd55bf287fcc67afa72821db3558bdc5ea7c"

[[files]]
file = "config/paxi/resourcepacks/drowning-in-sky-resourcepack/assets/drowning-in-sky/pinwheel/shaders/program/cloud_sea.fsh"
hash = "8925cb8a1684015206acbeae6157e877ccc757da5a3e1ca2f49dcda830c202d6"

[[files]]
file = "config/paxi/resourcepacks/drowning-in-sky-resourcepack/assets/drowning-in-sky/pinwheel/shaders/program/cloud_sea.json"
hash = "e03044ab700fce8f2e28eb3b30ee013a6bd2d0b3cd499566dd0916cb114d3753"

[[files]]
file = "config/paxi/resourcepacks/drowning-in-sky-resourcepack/pack.mcmeta"
hash = "ce486aa0cd8ac6ef07bff7ee9002d514cce27e6d9e0e7859decae83927613d35"

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "ea336d25c3e21ef168aec20e1ea470c96949ad29632646ee8e8ab0d74b4bbfc9"
metafile = true

[[files]]
file = "mods/create-aeronautics.pw.toml"
hash = "21110f3cc2edf33c680d3c8a680813288bcbd41122f2385ac976619dc37d7979"
metafile = true

[[files]]
file = "mods/create.pw.toml"
hash = "9da22561c3a5e45beb91121518a49f2e8a62bedb332574ce43a9d9b287ebc705"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
hash = "d3c9b48d7caa2ed964e5d1a4dab1da5655c63f0a7e4a59231c4369be7ffc30e1"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "73360e397134d238ee8fd21d33fd7f9275e9441f74f8f1b6ed92278877c0b9f1"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "5367193d3f87b7bc5a81bcd64a5b96a843e76d4df7a83c8bb7e1911aa82dd52e"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "58e0bebd41fa44f3f0dd6c053ec3eb1529d4bfe0c054c0741ba6e2e1b8e4523e"
metafile = true

[[files]]
file = "mods/lmft.pw.toml"
hash = "faed2d9ae09b810b385180a3c20e598ff4d43da75f324b0320649ea4eeb78e29"
metafile = true

[[files]]
file = "mods/moonlight.pw.toml"
hash = "c05fa3fa9bc5700104d928b616b15e70d441085dd060c6501122747dc3805de1"
metafile = true

[[files]]
file = "mods/paxi.pw.toml"
hash = "215d597764d5c5db89e700fc3495b72dc0a7f09c975de19dc8c580bde3469a5e"
metafile = true

[[files]]
file = "mods/sable.pw.toml"
hash = "a8ac5ced9cafa5cf53d9f4d0cb61df06729d1a7b66b88d6b5a2e609b1ca26fa0"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "0281ed9713f3141bdac363056a791845510e14761ea65b4b2813cf96d664b20a"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
hash = "fa0e1562f9dc89d6428546c7388dcfce8706843333d58f16cadce42b56b81085"
metafile = true

[[files]]
file = "mods/veil.pw.toml"
hash = "c48a5094a94604312b7876341c2116af7da589cef9d0d84b43f91afcbcb1049b"
metafile = true

[[files]]
file = "mods/yungs-api.pw.toml"
hash = "d9c0c9209bac0b693af2a7c1e47ffb28d366bad19c91df31dc6d345fa75250a1"
metafile = true

[[files]]
file = "unsup.ini"
hash = "2d70a62875ebc84371aad6694fa73d45b4621943a51ad1a54aada72e6ad1ee94"
