name = "Drowning in Sky"
author = "petrak@"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9ff569ddb1b9ca7a8c77cae667a635231641d0012657034d61ae168177bf21d8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
