name = "Drowning in Sky"
author = "petrak@"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dd5ebed775adc5acd69298ab46ee9c74011d78bfe153e310422dae8e460356e8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"

[options]
acceptable-game-versions = []
