name = "Drowning in Sky"
author = "petrak@"
version = "0.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "57948392a17725876c2d1ffad8246a47f459777b4cd25a69d42be01066ad5259"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"

[options]
acceptable-game-versions = []
